version: 2.1

parameters:
  image-name:
    type: string
    default: "udacity-capstone-hello-world"

executors:
  docker:
    docker:
      - image: docker:stable
  nodejs:
    docker:
      - image: circleci/node:14.15.0-stretch

workflows:
  k8s:
    jobs:
      - install
      - build-push-image:
          requires:
            - install
      - lint-dockerfile

jobs:
  install:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build-push-image:
    executor: docker
    environment:
      IMAGE_NAME: << pipeline.parameters.image-name >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ${IMAGE_NAME} .
            DOCKER_TAG=$(node -p "require('./package.json').version")
            echo ${DOCKER_TAG}
            docker tag ${IMAGE_NAME}:latest ${DOCKER_ID}/${IMAGE_NAME}:${DOCKER_TAG}
            docker tag ${DOCKER_ID}/${IMAGE_NAME}:${DOCKER_TAG} ${DOCKER_ID}/${IMAGE_NAME}:latest
            echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_ID} --password-stdin

  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint on Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
