version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable
  nodejs:
    docker:
      - image: circleci/node:14.15.0-stretch

workflows:
  k8s:
    jobs:
      - build
      - lint-dockerfile

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint on Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
